### ISSUE TITLE
Dynamic provision of Docker Agent Templates

### ISSUE THREAD

**Issue by galindro** [jenkinsci/docker-plugin#1036]
### What feature do you want to see added?

Would be great if this plugin could do something similar as what [Kubernetes plugin](https://plugins.jenkins.io/kubernetes/) does: it provides a high level pipeline step called `podTemplate`, which gives us the possibility to define the POD to be created dynamically via the pipeline.

This gives a lot of flexibility because we can define during pipeline execution which pod template do we want to use and also we can change their values before inform them to the podTemplate step.

My use case is: I have to spin up some docker containers which are tagged with our application version. Its cumbersome and massive to us to create a Docker Agent Template via JCasC everytime time a new Docker image is published. 

We unfortunately can't make use of docker-workflow-plugin because we run our containers in Windows (without WSL2) and such plugin [hardcodes cmd.exe](https://github.com/jenkinsci/docker-workflow-plugin/blob/master/src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java#L199) when the base image is a windows. Our pipeline needs bash.exe, so it can run in Linux and Windows without any issues.

**Comment by pjdarton** [comment]
Probably better to raise a PR on the docker workflow plugin
... although, fyi, that particular "run cat or cmd.exe" code is just to run a command that'll sit and do nothing (keeping the container alive) while all the real work is done by other docker commands running things on the container. You can still use bash in those.

Basically, this plugin is for building builds that don't know about docker, using docker to provide build agents for any builds.
The docker workflow plugin is for pipeline (aka workflow) builds that know they're using docker, that have opinions on how docker is used.
If you're using pipelines and your build knows it's doing docker stuff then you probably should be making the docker workflow plugin fit what you need rather than asking this one to replicate that one.

**Comment by CJCombrink** [comment]
I do agree with @pjdarton but at some point also wondered about such a feature.

I think the strongest point of this plugin is as commented "_building builds that don't know about docker_" 

For me it is also tedious to have to add templates each time for new base images. We tag a new image after each release, which happens probably at most 4 times a year, which creates 3 or more tags. Now and again we add new images.

I was wondering if there is a middle ground between CasC (we are not there yet) and some 'auto discovery' or templatization of templates. Where one can set a template or patter that then translate to an image to pull, using the same settings as those in the template. Just a crazy idea, not yet sure how feasible it would be, or what the options are. 

Crazy idea: In addition to 'labels' have a 'label-patterns' field where you specify for example `my-agent-(.*)`
Then a 'Docker Image Pattern' field that does `some-docker-image:$1`
and finally in the pipeline `agent { label 'my-agent-12' }`
Which causes the plugin to spin up a container from the image `some-docker-image:12`

I am not sure if this is supported by Jenkins or the plugin framework, because they will need to be able to support it before even considering something like that

**Comment by galindro** [comment]
@pjdarton, First of all ty very much for your fast response. This isn't normally what happens in Jenkins community in average...

I was expecting that you would come with such answer. Unfortunately, even though that particular "run cat or cmd.exe" code is just to run a command that'll sit and do nothing, if you try to do the bellow pipeline in a Windows Container, it will fail. It only works with powershell/bat/cmd steps. 

```groovy
def windows_server = docker.image('my-image:version')
windows_server.inside("") {
    script {
        sh("echo Hi!")
    }
}
```

Of course that maybe something like this could work, but that's exactly what we don't wanna do because we would then face other issues related to escaping characters, etc... Would be a nightmare.

```groovy
def windows_server = docker.image('my-image:version')
windows_server.inside("") {
    script {
        powershell("bash.exe -c 'echo Hi!'")
    }
}
```

That's why we decided to use this plugin instead of docker-workflow-plugin, because it respects the ENTRYPOINT of the image. Therefore, something like this works flawlessly:

```groovy
node('my-image-version') { // this is how we name the agent templates, to mimic the image names and tags
    sh("echo Hi!")
}
```

with this simple JCasC config:

```yaml
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://my-server:2375"
        readTimeout: 60
      exposeDockerHost: true
      name: "windows-docker"
      templates:
      - connector:
          jnlp:
            jnlpLauncher:
              webSocket: true
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          environment:
          - "JENKINS_WEB_SOCKET=true"
          environmentsString: "JENKINS_WEB_SOCKET=true"
          image: "my-image:version"
        labelString: "my-image-version"
        mode: EXCLUSIVE
        name: "my-image-version"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
```

I like the idea given by @CJCombrink. If it is possible to have it, would be great.

@CJCombrink : my reallity is even worse than yours: we have new releases in a daily basis. So, we would have to automate the JCasC changes, commit them, etc... A massive process.
