### ISSUE TITLE
Introduce how to use this plugin in a Pipeline

### ISSUE THREAD

**Issue by WilliamShoww** [jenkinsci/docker-plugin#1077]
### Describe your use-case which is not covered by existing documentation.

The document introduces how to configure Jenkins free-style projects, but does not introduce how to write pipeline scripts for pipeline projects.

### Are you interested in contributing to the documentation?

Interested, but I don’t know how to use this plug-in jenkins pipeline project

**Comment by MarkEWaite** [comment]
Thanks for the report @WilliamShoww .

I'm not sure of the best way to describe using the plugin with Pipeline, since it is not specific to Pipeline.  Here is an example that I use to test the plugin.

The following Pipeline job uses an agent with the 'alpine' label defined on my controller.  

```groovy
pipeline {
    agent {
        label 'alpine'
    }
    stages {
        stage('Hello from Alpine docker agent') {
            steps {
                sh 'whoami && uname -a && cat /etc/os-release && java -version && git --version'
            }
        }
    }
}
```

All agents with the label 'alpine' on my controller are started by the docker plugin when requested, then stopped by the docker plugin when the job completes.  When I ran that job, the console output reported:

```bash
Started by user Mark Waite
[Pipeline] Start of Pipeline
[Pipeline] node
Running on alpine-jdk21-00048adis7zag on mark-pc2 in /home/jenkins/agent/workspace/alpine-whoami
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Hello from Alpine docker agent)
[Pipeline] sh
+ whoami
jenkins
+ uname -a
Linux abf179eeac7d 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 Linux
+ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
+ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)
+ git --version
git version 2.43.0
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Gitea] do not publish assets due to source being no GiteaSCMSource
Finished: SUCCESS
```

In the configuration as code definition for my Jenkins controller, I have the following entry:

```yaml
jenkins:
  clouds:
  - docker:
      containerCap: 3
      dockerApi:
        connectTimeout: 23
        dockerHost:
          uri: "tcp://docker-host.markwaite.net:2375"
        readTimeout: 43
      errorDuration: 313
      name: "mark-pc2"
      templates:
      - connector:
          jnlp:
            jenkinsUrl: "http://mark-pc2.markwaite.net}:8080/"
            user: "1000"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jenkins/inbound-agent:3248.v65ecb_254c298-2-alpine-jdk21"
        labelString: "alpine jdk21 alpine-jdk21 git-2.43"
        name: "alpine-jdk21"
        pullTimeout: 171
        remoteFs: "/home/jenkins/agent"
```

That configuration as code entry describes the agent definition for the 'alpine' label.  I 

Does that help answer your question?

Is the example the key part of that or does it also need an explanation that the docker plugin creates new agents based on labels requested by jobs.  Those jobs can be Pipeline, freestyle, or matrix jobs.
